name: PointsOfInterest
main: crussell52.poi.PointsOfInterest
version: 0.1.2
commands:
    poi:
       description: Show your friends what's interesting in the world!
       usage: |
           Use "/poi help" for guidance.
           
