#####
#
# Use spaces in this file instead of tabs -- tabs will make it... not happy.
#
# POI = Point of Interest
#
#####

######
#
#  distanceThreshold:
#
#    Controls the maximum search radius and the maximum distance at which
#    a player can get directions to a POI. Set to a value of -1 for "unlimited"
#
#    Type: Whole Number
#    Default: 2000
#    
######
distanceThreshold: 2000

######
#
#  minPoiGap:
#
#    Controls the minimum distance between POIs.  A player will not be able to create
#    a POI within this distance of another POI.
#
#    Type: Whole Number, not negative
#    Default: 50
#    
######
minPoiGap: 50

######
#
#  maxSearchResults:
#
#    Maximum number of results that will be returned when player 
#    searches for nearby POIs.
#
#    Type: Whole Number, larger than 0 (zero)
#    Default: 10
#    
######
maxSearchResults: 10

######
#
#  maxPlayerPoiPerWorld:
#
#    Maximum number of POIs each player can create in each world. If this value
#    is reduced and a player has already created more than the new max, the player
#    will NOT be forced to clean up the excess POIs.  It is recommended that this number
#    starts lower and is only increased.
#
#    Type: Whole Number, larger than 0 (zero)
#    Default: 10
#    
######
maxPlayerPoiPerWorld: 10

######
#
#  worldBlacklist:
#
#    A list of worlds which do not allow POIs. If a world with existing POIs is added
#    to the black list, those POIs will NOT be automatically deleted; however, players 
#    (including POI owners) will not be able to see nor interact with the POIs within
#    that world.  If the world is removed from the blacklist, the POIs will become
#    available to the players again.
#
#    Type: [world1, world1_nether, etc]
#    Default: none
#    
######
worldBlacklist: 