name: RubySlippers
main: crussell52.RubySlippers.RubySlippers
version: 0.1.3
commands:
    rs:
       description: Are you a good witch or a bad witch?
       usage: |
              /<command> kansas - Set your home
              /<command> tap - There's no place like home.
              /<command> cost - Nothing is for free.
       
